### ISSUE TITLE
Python List Quiz

### ISSUE THREAD

**Issue by FilipBolt** [FilipBolt/nlp_ramp_up#53]
You have one hour to complete the following three problems: 

1. https://pythonprinciples.com/challenges/Capital-indexes/

2. https://pythonprinciples.com/challenges/Thousands-separator/

3. https://pythonprinciples.com/challenges/Writing-short-code/

**Comment by F0R-L00P** [comment]
#`# buil function to return index of capitalized word in list
def capital_indexes(s):
    index_list = []
    for i in range(len(s)):
        if s[i] == s[i].upper():
            index_list.append(i)
    return index_list

# build function to sperate at housand and convert int to string
def format_number(number):
    return "{:,}".format(number)


# build function in 1 line, append list int to newlist in str
def convert(my_list):
    return [str(my_list[i]) for i in range(len(my_list))]`

**Comment by F0R-L00P** [comment]
# #
